// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {core} from '../models';
import {workspace} from '../models';

export function DetectFramework(arg1:string):Promise<string>;

export function Drivers():Promise<Array<string>>;

export function InspectProject(arg1:string):Promise<app.ProjectInfo>;

export function ListEndpoints():Promise<Array<core.Endpoint>>;

export function OpenProject(arg1:string):Promise<workspace.Workspace>;

export function SelectProjectFolder():Promise<string>;
