// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {app} from '../models';
import {httpclient} from '../models';
import {domain} from '../models';
import {workspace} from '../models';

export function ClearProjectAuth(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DetectFramework(arg1:string):Promise<string>;

export function DetectProject(arg1:string):Promise<core.DetectionResult>;

export function Drivers():Promise<Array<string>>;

export function ExecuteRequest(arg1:app.ExecuteRequestInput):Promise<httpclient.Response>;

export function GetActiveProjectID():Promise<string>;

export function GetProjectAuth(arg1:string):Promise<app.ProjectAuthState>;

export function GetProjectStats(arg1:string):Promise<domain.ProjectStats>;

export function InspectProject(arg1:string):Promise<app.ProjectInfo>;

export function ListEndpoints(arg1:string):Promise<Array<core.Endpoint>>;

export function ListProjects():Promise<Array<domain.Project>>;

export function MarkProjectSynced(arg1:string):Promise<void>;

export function OpenProject(arg1:string):Promise<workspace.Workspace>;

export function PreviewAPIRoutes(arg1:string,arg2:string,arg3:string):Promise<app.APIDetection>;

export function SaveProject(arg1:domain.ProjectInput):Promise<domain.Project>;

export function ScanActiveProject():Promise<Array<core.Endpoint>>;

export function ScanWorkspace(arg1:string):Promise<Array<core.Endpoint>>;

export function SelectProjectFolder():Promise<string>;

export function SetActiveProjectID(arg1:string):Promise<void>;

export function SetProjectAuthManual(arg1:app.SetProjectAuthInput):Promise<void>;

export function UpdateProjectAuthRoutes(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateProjectBaseURL(arg1:string,arg2:string):Promise<void>;
