// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectFramework(arg1) {
  return window['go']['app']['App']['DetectFramework'](arg1);
}

export function Drivers() {
  return window['go']['app']['App']['Drivers']();
}

export function InspectProject(arg1) {
  return window['go']['app']['App']['InspectProject'](arg1);
}

export function ListEndpoints() {
  return window['go']['app']['App']['ListEndpoints']();
}

export function OpenProject(arg1) {
  return window['go']['app']['App']['OpenProject'](arg1);
}

export function SelectProjectFolder() {
  return window['go']['app']['App']['SelectProjectFolder']();
}
