// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {app} from '../models';
import {httpclient} from '../models';
import {domain} from '../models';
import {workspace} from '../models';

export function ClearCapturedValues(arg1:string):Promise<void>;

export function ClearHistory(arg1:string):Promise<void>;

export function ClearProjectAuth(arg1:string):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DetectFramework(arg1:string):Promise<string>;

export function DetectProject(arg1:string):Promise<core.DetectionResult>;

export function Drivers():Promise<Array<string>>;

export function ExecuteRequest(arg1:app.ExecuteRequestInput):Promise<httpclient.Response>;

export function ExportOpenAPI(arg1:string):Promise<string>;

export function GetActiveProjectID():Promise<string>;

export function GetDashboardMetrics(arg1:string,arg2:number):Promise<app.DashboardMetrics>;

export function GetHistoryEntry(arg1:string):Promise<app.HistoryEntryDetail>;

export function GetProjectAuth(arg1:string):Promise<app.ProjectAuthState>;

export function GetProjectStats(arg1:string):Promise<domain.ProjectStats>;

export function GetProjectStatsReport(arg1:string):Promise<core.StatsReport>;

export function GetSnapshotDiff(arg1:string):Promise<app.SnapshotDiff>;

export function InspectProject(arg1:string):Promise<app.ProjectInfo>;

export function ListCapturedValues(arg1:string):Promise<Array<app.CapturedValueDTO>>;

export function ListCollections(arg1:string):Promise<Array<app.CollectionDTO>>;

export function ListEndpointCaptures(arg1:string,arg2:string):Promise<Array<app.EndpointCaptureDTO>>;

export function ListEndpointTests(arg1:string,arg2:string):Promise<Array<app.EndpointTestDTO>>;

export function ListEndpoints(arg1:string):Promise<Array<core.Endpoint>>;

export function ListEnvironments(arg1:string):Promise<Array<app.EnvironmentDTO>>;

export function ListHistory(arg1:string,arg2:number):Promise<Array<app.HistoryListItem>>;

export function ListProjects():Promise<Array<domain.Project>>;

export function ListSnapshots(arg1:string,arg2:number):Promise<Array<app.SnapshotSummary>>;

export function MarkProjectSynced(arg1:string):Promise<void>;

export function OpenProject(arg1:string):Promise<workspace.Workspace>;

export function PreviewAPIRoutes(arg1:string,arg2:string,arg3:string):Promise<app.APIDetection>;

export function RegenerateBodyValues(arg1:app.RegenerateBodyInput):Promise<string>;

export function RegenerateExampleBody(arg1:string):Promise<string>;

export function RunCollection(arg1:string):Promise<app.CollectionRunDTO>;

export function SaveCollection(arg1:app.SaveCollectionInput):Promise<app.CollectionDTO>;

export function SaveEndpointCaptures(arg1:app.SaveCapturesInput):Promise<void>;

export function SaveEndpointTests(arg1:app.SaveTestsInput):Promise<void>;

export function SaveEnvironment(arg1:app.SaveEnvironmentInput):Promise<app.EnvironmentDTO>;

export function SaveOpenAPIToFile(arg1:string):Promise<string>;

export function SaveProject(arg1:domain.ProjectInput):Promise<domain.Project>;

export function ScanActiveProject():Promise<Array<core.Endpoint>>;

export function ScanWorkspace(arg1:string):Promise<Array<core.Endpoint>>;

export function SelectProjectFolder():Promise<string>;

export function SetActiveEnvironment(arg1:string,arg2:string):Promise<void>;

export function SetActiveProjectID(arg1:string):Promise<void>;

export function SetProjectAuthManual(arg1:app.SetProjectAuthInput):Promise<void>;

export function UpdateProjectAuthRoutes(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateProjectBaseURL(arg1:string,arg2:string):Promise<void>;
