// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory(arg1) {
  return window['go']['app']['App']['ClearHistory'](arg1);
}

export function ClearProjectAuth(arg1) {
  return window['go']['app']['App']['ClearProjectAuth'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['app']['App']['DeleteEnvironment'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function DetectFramework(arg1) {
  return window['go']['app']['App']['DetectFramework'](arg1);
}

export function DetectProject(arg1) {
  return window['go']['app']['App']['DetectProject'](arg1);
}

export function Drivers() {
  return window['go']['app']['App']['Drivers']();
}

export function ExecuteRequest(arg1) {
  return window['go']['app']['App']['ExecuteRequest'](arg1);
}

export function ExportOpenAPI(arg1) {
  return window['go']['app']['App']['ExportOpenAPI'](arg1);
}

export function GetActiveProjectID() {
  return window['go']['app']['App']['GetActiveProjectID']();
}

export function GetDashboardMetrics(arg1, arg2) {
  return window['go']['app']['App']['GetDashboardMetrics'](arg1, arg2);
}

export function GetHistoryEntry(arg1) {
  return window['go']['app']['App']['GetHistoryEntry'](arg1);
}

export function GetProjectAuth(arg1) {
  return window['go']['app']['App']['GetProjectAuth'](arg1);
}

export function GetProjectStats(arg1) {
  return window['go']['app']['App']['GetProjectStats'](arg1);
}

export function GetProjectStatsReport(arg1) {
  return window['go']['app']['App']['GetProjectStatsReport'](arg1);
}

export function GetSnapshotDiff(arg1) {
  return window['go']['app']['App']['GetSnapshotDiff'](arg1);
}

export function InspectProject(arg1) {
  return window['go']['app']['App']['InspectProject'](arg1);
}

export function ListEndpointTests(arg1, arg2) {
  return window['go']['app']['App']['ListEndpointTests'](arg1, arg2);
}

export function ListEndpoints(arg1) {
  return window['go']['app']['App']['ListEndpoints'](arg1);
}

export function ListEnvironments(arg1) {
  return window['go']['app']['App']['ListEnvironments'](arg1);
}

export function ListHistory(arg1, arg2) {
  return window['go']['app']['App']['ListHistory'](arg1, arg2);
}

export function ListProjects() {
  return window['go']['app']['App']['ListProjects']();
}

export function ListSnapshots(arg1, arg2) {
  return window['go']['app']['App']['ListSnapshots'](arg1, arg2);
}

export function MarkProjectSynced(arg1) {
  return window['go']['app']['App']['MarkProjectSynced'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['app']['App']['OpenProject'](arg1);
}

export function PreviewAPIRoutes(arg1, arg2, arg3) {
  return window['go']['app']['App']['PreviewAPIRoutes'](arg1, arg2, arg3);
}

export function RegenerateBodyValues(arg1) {
  return window['go']['app']['App']['RegenerateBodyValues'](arg1);
}

export function RegenerateExampleBody(arg1) {
  return window['go']['app']['App']['RegenerateExampleBody'](arg1);
}

export function SaveEndpointTests(arg1) {
  return window['go']['app']['App']['SaveEndpointTests'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['app']['App']['SaveEnvironment'](arg1);
}

export function SaveOpenAPIToFile(arg1) {
  return window['go']['app']['App']['SaveOpenAPIToFile'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['app']['App']['SaveProject'](arg1);
}

export function ScanActiveProject() {
  return window['go']['app']['App']['ScanActiveProject']();
}

export function ScanWorkspace(arg1) {
  return window['go']['app']['App']['ScanWorkspace'](arg1);
}

export function SelectProjectFolder() {
  return window['go']['app']['App']['SelectProjectFolder']();
}

export function SetActiveEnvironment(arg1, arg2) {
  return window['go']['app']['App']['SetActiveEnvironment'](arg1, arg2);
}

export function SetActiveProjectID(arg1) {
  return window['go']['app']['App']['SetActiveProjectID'](arg1);
}

export function SetProjectAuthManual(arg1) {
  return window['go']['app']['App']['SetProjectAuthManual'](arg1);
}

export function UpdateProjectAuthRoutes(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateProjectAuthRoutes'](arg1, arg2, arg3, arg4);
}

export function UpdateProjectBaseURL(arg1, arg2) {
  return window['go']['app']['App']['UpdateProjectBaseURL'](arg1, arg2);
}
